# Gotta Catch em All: Listing the Strongest Pokemon

## 1. Import Libraries and Dependencies

In [1]:
# import libraries and dependencies
import pandas as pd
from pathlib import Path

## 2. Set the File Path to the CSV using Pathlib

In [2]:
# Set the path of the Pokemon csv file to be loaded from the Resources folder.
# Define the path name as pokemon_path
pokemon_path = Path("./Resources/Pokemon.csv")

## 3. Import the CSV into Pandas DataFrame

In [3]:
# Define a variable "pokemon_df" and store the Pokemon.csv into Pandas DataFrame using the pokemon_path
pokemon_df = pd.read_csv(pokemon_path)
# Print out the first 5 rows.
pokemon_df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

## 4. View Summary Statistics

In [4]:
# Use the describe function on pokemon_df to review general info on Total percentiles.
pokemon_df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

## 5. Create Bins for Total Ranking

In [5]:
# Create the variable bins to define our bounds for when we cut the dataframe.
# Bins are 0, 330, 450, 515, 600, 700, 800
bins = [0, 330, 450,515, 600, 700, 800]
# Create names for the bins
# group_names to be "Very Weak", "Weak", "Moderate", "Strong", "Very Strong", "Over Powered"
group_names = ["Very Weak", "Weak", "Moderate", "Strong", "Very Strong", "Over Powered"]
pokemon_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

## 6. Label Records According to the Corresponding Bin

In [6]:
# Add a column named "Total Ranking" to pokemon_df and slice the data into the bins
pokemon_df["Total Ranking"] = pd.cut(pokemon_df["Total"], bins, labels=group_names)
# Print out the first 10 rows of pokemon_df.
pokemon_df.head(30)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total Ranking
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Very Weak
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Weak
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,Strong
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,Very Strong
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Very Weak
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False,Weak
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False,Strong
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False,Very Strong
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False,Very Strong
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False,Very Weak
10,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False,Weak
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False,Strong
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False,Very Strong
13,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False,Very Weak
14,11,Metapod,Bug,NaN,205,50,20,55,25,25,30,1,False,Very Weak
15,12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,1,False,Weak
16,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False,Very Weak
17,14,Kakuna,Bug,Poison,205,45,25,50,25,25,35,1,False,Very Weak
18,15,Beedrill,Bug,Poison,395,65,90,40,45,80,75,1,False,Weak
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,Moderate
20,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False,Very Weak
21,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False,Weak
22,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False,Moderate
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False,Strong
24,19,Rattata,Normal,NaN,253,30,56,35,25,35,72,1,False,Very Weak
25,20,Raticate,Normal,NaN,413,55,81,60,50,70,97,1,False,Weak
26,21,Spearow,Normal,Flying,262,40,60,30,31,31,70,1,False,Very Weak
27,22,Fearow,Normal,Flying,442,65,90,65,61,61,100,1,False,Weak
28,23,Ekans,Poison,NaN,288,35,60,44,40,54,55,1,False,Very Weak
29,24,Arbok,Poison,NaN,438,60,85,69,65,79,80,1,False,Weak

## 7. Set the Index to the DataFrame

In [7]:
# Set new index to Total Ranking
pokemon_df.set_index("Total Ranking")

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Total Ranking,,,,,,,,,,,,,
Very Weak,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
Weak,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
Strong,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
Very Strong,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
Very Weak,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Strong,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
Very Strong,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
Strong,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
Very Strong,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
Strong,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

## 8. Filter Down to the Strongest Pokemon

In [8]:
# Set the variable overpowered_df to be the pokemon dataframe with Over Powered only.
overpowered_df = pokemon_df.loc[pokemon_df["Total Ranking"] == "Over Powered", :]
overpowered_df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total Ranking
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,780,106,190,100,154,100,130,1,True,Over Powered
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,780,106,150,70,194,120,140,1,True,Over Powered
422,382,KyogrePrimal Kyogre,Water,NaN,770,100,150,90,180,160,90,3,True,Over Powered
424,383,GroudonPrimal Groudon,Ground,Fire,770,100,180,160,150,90,90,3,True,Over Powered
426,384,RayquazaMega Rayquaza,Dragon,Flying,780,105,180,100,180,100,115,3,True,Over Powered
552,493,Arceus,Normal,NaN,720,120,120,120,120,120,120,4,True,Over Powered